version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: memes_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d memes_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    volumes:
      - ./app:/app
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/memes_db
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_NAME: memes
    ports:
      - "8000:8000"

  media_service:
    build:
      context: .
      dockerfile: Dockerfile.media_service
    depends_on:
      minio:
        condition: service_started
      db:
        condition: service_healthy
    volumes:
      - ./media_service:/media_service
    environment:
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minio
      S3_SECRET_KEY: minio123
      S3_BUCKET_NAME: memes
    ports:
      - "8001:8001"

volumes:
  postgres_data:
  minio_data:
