FROM python:3.10-slim

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY ./media_service /media_service

CMD ["uvicorn", "media_service.main:app", "--host", "0.0.0.0", "--port", "8001"]
